# TOOL metabarcoding-deseq2.R: "Differential OTU abundance analysis using DESeq2" (Tests for OTU differential abundances using DESeq2. A Benjamini-Hochberg multiple inference correction is applied to the data, with OTUs filtered using a cut-off value of 0.01. While the analysis can be performed using a phenodata variable comprising >2 sample groups, output files are restricted to comparisons between two groups. Produces a result table and plots OTU differential abundances at a user-specified level of biological organization. Requires a phyloseq object converted into the DESeq2 format as the input, i.e. the file \"deseq2.Rda\" generated by the \"Transform OTU counts\" tool. Note that the input file should not contain transformed OTU counts \(raw count data are required\).)
# INPUT deseq2.Rda: "DESeq2 data in .Rda format" TYPE GENERIC
# OUTPUT deseq2_otuplot.pdf: deseq2_otuplot.pdf
# OUTPUT deseq2_otutable.tsv: deseq2_otutable.tsv
# PARAMETER howmany: "No. of sample groups under the phenodata variable" TYPE [two: "2", abovetwo: ">2"] DEFAULT two (How many sample groups are there under the phenodata variable used for the analysis?)
# PARAMETER yaxtax: "Lower-level taxonomic grouping for differential abundance plot" TYPE [Class: "Class", Order: "Order", Family: "Family", Genus: "Genus"] DEFAULT Class (Lower-level taxonomic classification used for differential abundance plotting\; default is class. The level selected here should be lower than that selected under the \"Higher-level taxonomic grouping...\" menu. Note: OTUs classified as NA at this level are filtered out to enable clearer plots.)
# PARAMETER legtax: "Higher-level taxonomic grouping for differential abundance plot" TYPE [Phylum: "Phylum", Class: "Class", Order: "Order", Family: "Family"] DEFAULT Phylum (Higher-level taxonomic classification used for differential abundance plotting; default is phylum. The level chosen here should be higher than that selected under the \"Lower-level taxonomic grouping...\" menu.)
# PARAMETER OPTIONAL group1: "Group 1 for DESeq2 contrasts (if >2 groups overall)" TYPE STRING DEFAULT empty (First sample group name (one of the sample groups under the phenodata variable used for the analysis\))
# PARAMETER OPTIONAL group2: "Group 2 for DESeq2 contrasts (if >2 groups overall)" TYPE STRING DEFAULT empty (Second sample group name (one of the sample groups under the phenodata variable used for the analysis\))
# RUNTIME R-3.6.1-phyloseq

# JH 2020

# Load packages
library(DESeq2)
library(ggplot2)
library(phyloseq)

# Load data
load("deseq2.Rda")

# DESeq2
# Using default fitType (parametric)

diagdds <- DESeq(diagdds, fitType = "parametric")
if (howmany == "two"){ 
	res <- results(diagdds)
}
if (howmany == "abovetwo"){ 
	res = results(diagdds, 
		contrast=c(group_column1, # Phenodata variable (from "Transform OTU..." tool)
				group1, group2)) # Groups under selected phenodata variable
}

# Tabulate results as data frame including taxonomic classifications with FDR cut-off (0.01)
# (Taxonomic info is fetched from phyloseq object)
res <- res[order(res$padj, na.last = NA), ]
alpha = 0.01
sigtab = res[(res$padj < alpha), ]
sigtab = cbind(as(sigtab, "data.frame"), 
	as(tax_table(ps0)[rownames(sigtab), ], "matrix")) # ps0 = phyloseq object without VST transformation

# Tidier result table for tool output
sigtab_tidy <- sigtab[, c("baseMean", "log2FoldChange", "lfcSE", "padj", 
				"Phylum", "Class", "Order", "Family", "Genus")]

# Differential abundance plot
sigtab_plot <- subset(sigtab, 
	yaxtax != "NA", !is.na(yaxtax)) # Filter out NA OTUs at lower taxonomic level
# Higher-level taxonomic groupings
x <- tapply(sigtab_plot$log2FoldChange, sigtab_plot[, legtax], function(x) max(x))
x <- sort(x, TRUE)
sigtab_plot[, legtax] = factor(as.character(sigtab_plot[, legtax]), levels = names(x))
# Lower-level taxonomic groupings
x <- tapply(sigtab_plot$log2FoldChange, sigtab_plot[, yaxtax], function(x) max(x))
x <- sort(x, TRUE)
sigtab_plot[, yaxtax] = factor(as.character(sigtab_plot[, yaxtax]), levels = names(x))

# Open report PDF
pdf("deseq2_otuplot.pdf", width = 7, height = 5)

ggplot(sigtab_plot,
	aes(y = get(yaxtax), 
               x = log2FoldChange, 
               color = get(legtax))) + 
			geom_vline(xintercept = 0.0, color = "gray", size = 0.5) +
			geom_point(size=6) + 
			theme(axis.text.x = element_text(angle = -90, 
		                                       hjust = 0, vjust=0.5)) +
			xlab(expression(Log[2]*" fold change")) + 
			ylab(yaxtax) +
			scale_colour_discrete(name = legtax)

# Close report PDF
dev.off()

# Write DESeq2 result table as TSV
write.table(sigtab_tidy, file = "deseq2_otutable.tsv", 
	sep = "\t", row.names = T, col.names = T, quote = F)
