# TOOL mothur-classify-counttable.R: "Produce count table and phenodata" (This tool generates a count table and a phenodata file, which you can use to assign samples to different experimental groups for further statistical analyses. As inputs you need the sequence taxonomy assignment file and the count file generated by Mothur.)
# INPUT OPTIONAL picked.count_table: "Mothur count file" TYPE MOTHUR_COUNT
# INPUT sequences-taxonomy-assignment.txt: "Sequences taxonomy assignment file" TYPE GENERIC
# OUTPUT counttable.tsv: counttable.tsv
# OUTPUT META phenodata.tsv: phenodata.tsv
# OUTPUT OPTIONAL counttable_transposed.tsv: counttable_transposed.tsv
# PARAMETER OPTIONAL cutlevel: "Cutting level for taxonomic names" TYPE INTEGER FROM 0 TO 9 DEFAULT 0 (Cutting level for taxonomic names for the count table. 0 means retain full names, e.g. Bacteria;Actinobacteria;Actinobacteria;Coriobacteridae;Coriobacteriales;Coriobacterineae;Coriobacteriaceae;Slackia;unclassified.)
# PARAMETER OPTIONAL rarefy: "Rarefy counts" TYPE [yes, no] DEFAULT no (Should sequence counts be rarefied? Normally your samples have different number of sequences. If you select yes here, the count table will be subsampled so that each sample has the same number of sequences as your smallest sample. Please note that the species, whose counts after rarefying are zero in all samples, are removed.)
# PARAMETER OPTIONAL binarytable: "Produce binary table instead of counts" TYPE [yes, no] DEFAULT no (Should the actual sequence counts be converted to 0 and 1, indicating the presence and absence of species? This kind of binary table is typically used when studying the co-occurence of species.)


# OUTPUT OPTIONAL log.txt

# ML 23.3.2017 detach from mothur-classify.seqs
# JT 25.8.2018 change the way counttable is generated, add the binary option
# EK 30.8.2018 added transposed count table compatible with edgeR and DESeq2 tools
# JT 31.8.2018 added rarefy parameter
# JT 20.12.2018 remove those species whose rarefied counts are zero in all samples, the same seed is used so that the results don't vary from run to run.

library(reshape2)


# binary
binary <- c(file.path(chipster.tools.path, "mothur", "mothur"))

# Count table and phenodata preparations:

# Reads the data and tabulates it
pick <- read.table("picked.count_table", header=T, sep="\t")
tax  <- read.table("sequences-taxonomy-assignment.txt", header=F, sep="\t")
dat  <- merge(pick, tax, by.x="Representative_Sequence", by.y="V1")
dat$V2<-gsub(".[[:digit:]]{1,}.?[[:digit:]]?)", "", as.character(dat$V2))


# Cutting the taxonomic names
if(cutlevel==0) {
	dat$newnames<-dat$V2
} else {
	sp<-strsplit(dat$V2, ";")
	sp2<-rep(NA, nrow(dat))
	for(i in 1:nrow(dat)) {
		sp2[i]<-paste(sp[[i]][1:cutlevel], collapse=";")
	}
	dat$newnames<-sp2
}


# Setting up the final result
data_start <- which(colnames(dat) == "total") + 1
data_end <- which(colnames(dat) == "V2") - 1
names_col <- which(colnames(dat) == "newnames")

# Same manipulations here
dat <- dat[,c(names_col, data_start:data_end)]
datm <- melt(dat)
a <- aggregate(datm$value, list(datm$newnames, datm$variable), function(x) sum(x, na.rm=T))
b <- dcast(a, Group.2~Group.1)
rownames(b) <- b$Group.2
b <- b[,-1]

# Rarefying
#if(nmax == 0 & rarefy == "yes") {  # we can add nmax parameter later
#	nmax <- min(rowSums(b))
#}
if(rarefy == "yes") {
	nmax <- min(rowSums(b))
	btmp <- apply(b, 1, function(x) rep(colnames(b), times=x))
	seed <- 1234
	set.seed(seed)
	btmp <- lapply(btmp, function(x) sample(x, size=nmax, replace=F))
	btmp <- lapply(btmp, function(x) table(factor(x, levels=colnames(b))))
	b <- t(do.call(cbind, btmp))
#	# deleted.columns <- colnames(b)[which(colSums(b)==0)] 
	b <- b[,-which(colSums(b)==0)]
}

# Produce binary table (0/1) showing only if a specie is present or absent, rather than the actual sequence counts        
if(binarytable == "yes") {
	b[b>0] <- 1
}

tab <- b

# Writing the table to disk
write.table(tab, "counttable.tsv", col.names=T, row.names=T, sep="\t", quote=FALSE)
write.table(data.frame(sample=rownames(tab), chiptype="NGS", group=rep("", length(rownames(tab)))), "phenodata.tsv", col.names=T, row.names=F, sep="\t", quote=F)

# Transpose the table, add "chip." to column names to make it compatible with DESeq2 and edgeR tools, and write it to disk.
# Rarefied counts should not be used in DEseq2 and edgeR, so we don't make the transposed table if the rarefy=yes.
if(rarefy == "no") {
	oldtable <- read.table("counttable.tsv",header = TRUE, sep = "\t", check.names = FALSE)
	newtable <- t(oldtable)
	colnames(newtable) <- paste("chip", colnames(newtable), sep = ".")
	write.table(newtable, "counttable_transposed.tsv", quote = FALSE, sep = "\t")
}
	

	