# TOOL mothur-classify-counttable_2018-07-12.R: "Produce count table and phenodata" (This tool generates a count table and a phenodata file, which you can use to assign samples to different experimental groups for further statistical analyses. As inputs you need a sequence taxonomy assignment file, a groups file and a count file generated by Mothur.)
# INPUT OPTIONAL picked.count_table: "Mothur count file" TYPE MOTHUR_COUNT
# INPUT OPTIONAL all.grp: "Groups file" TYPE MOTHUR_GROUPS 
# INPUT OPTIONAL sequences-taxonomy-assignment.txt: "Sequence taxonomy assignment" TYPE GENERIC 
# OUTPUT counttable.tsv: counttable.tsv 
# OUTPUT META phenodata.tsv: phenodata.tsv 
# PARAMETER OPTIONAL cutlevel: "Cutting level for taxonomic names" TYPE INTEGER FROM 0 TO 9 DEFAULT 0 (Cutting level for taxonomic names for the count table. 0 means retain full names, e.g. Bacteria;Actinobacteria;Actinobacteria;Coriobacteridae;Coriobacteriales;Coriobacterineae;Coriobacteriaceae;Slackia;unclassified.)


# OUTPUT OPTIONAL log.txt

# ML 23.3.2017 detach from mothur-classify.seqs
# JT 8.8.2018 change the way counttable is generated

library(reshape2)

# binary
binary <- c(file.path(chipster.tools.path, "mothur", "mothur"))

	
# Count table and phenodata preparations:

# Reads the data and tabulates it
pick <- read.table("picked.count_table", header=T, sep="\t")                  # change file name (Costello: stool.trim.unique.good.filter.unique.precluster.pick.count_table)
tax  <- read.table("sequences-taxonomy-assignment.txt", header=F, sep="\t")   # change file name (Costello: stool.trim.unique.good.filter.unique.precluster.pick.rdp.wang.taxonomy)
dat  <- merge(pick, tax, by.x="Representative_Sequence", by.y="V1")
dat2 <- dat
dat2$V2<-gsub(".[[:digit:]]{1,}.?[[:digit:]]?)", "", as.character(dat2$V2))

		
# Cutting the taxonomic names
	if(cutlevel==0) {
		dat2$newnames<-dat2$V2
	} else {
		sp<-strsplit(dat2$V2, ";")
		sp2<-rep(NA, nrow(dat2))
		for(i in 1:nrow(dat2)) {
			sp2[i]<-paste(sp[[i]][1:cutlevel], collapse=";")
		}
		dat2$newnames<-sp2
	}

# Setting up the final result
data_start <- which(colnames(dat2) == "total") + 1
data_end <- which(colnames(dat2) == "V2") - 1
names_col <- which(colnames(dat2) == "newnames")	

# Same weird manipulations here
dat2 <- dat2[,c(names_col, data_start:data_end)]
dat2m <- melt(dat2)
a <- aggregate(dat2m$value, list(dat2m$newnames, dat2m$variable), function(x) sum(x, na.rm=T))
b <- dcast(a, Group.2~Group.1)
rownames(b) <- b$Group.2
b <- b[,-1]

# Should be 0/1 or not?
yesno <- FALSE                                                                # Tälle uusi optio?
if(yesno) {
   b[b>0] <- 1
}

tab <- b


# Set chiptype
chiptype<-c("NGS")

	
# Writing the table to disk
	write.table(tab, "counttable.tsv", col.names=T, row.names=T, sep="\t", quote=FALSE)
	write.table(data.frame(sample=rownames(tab), chiptype=chiptype, group=rep("", length(rownames(tab)))), "phenodata.tsv", col.names=T, row.names=F, sep="\t", quote=F)
	
	
	
