# TOOL single-cell-extract-information.R: "Extract information from Seurat object" (This tool extracts data from Seurat object.)  
# INPUT OPTIONAL seurat_obj.Robj: "Seurat object" TYPE GENERIC
# INPUT OPTIONAL combined_seurat_obj.Robj: "Combined seurat object" TYPE GENERIC
# INPUT OPTIONAL reference: "Seurat object stored in an RDS file " TYPE GENERIC 
# OUTPUT OPTIONAL slots.txt
# OUTPUT OPTIONAL meta_data.tsv
# OUTPUT OPTIONAL gene_list.tsv
# OUTPUT OPTIONAL cell_list.tsv
# PARAMETER OPTIONAL gene_list: "Do you want to exract a list of the genes?" TYPE [yes, no] DEFAULT no
# PARAMETER OPTIONAL cell_list: "Do you want to exract a list of the cells?" TYPE [yes, no] DEFAULT no
# PARAMETER OPTIONAL meta_data: "Do you want to exract the meta data table" TYPE [yes, no] DEFAULT no
# RUNTIME R-4.2.3-single-cell
# TOOLS_BIN ""  

library(dplyr, quietly = TRUE)
library(Seurat, quietly = TRUE)

# Load the R-Seurat-object (called seurat_obj)
if (file.exists("reference") ){
	seurat_obj <- readRDS("reference")
}
if (file.exists("seurat_obj.Robj") ){
	load("seurat_obj.Robj")
}
if (file.exists("combined_seurat_obj.Robj") ){
	load("combined_seurat_obj.Robj")
	seurat_obj <- data.combined
}

# Create a text file containing the different data slots in the Seurat object
sink("slots.txt")

print("Assays in the seurat object: ")
print(seurat_obj@assays)
print("Active assay in the object: ")
print(seurat_obj@active.assay)
print("Active cluster identity in the cluster: ")
print(head(seurat_obj@active.ident))
print("List of graph objects in the seurat object:")
print(seurat_obj@graphs)
print("List of neighbor objects in the seurat object:")
print(seurat_obj@neighbors)
print("List of dimensional reductions for this object:")
print(seurat_obj@reductions)
print("List of spatial image objects in this object:")
print(seurat_obj@images)
print("Name of the project:")
print(seurat_obj@project.name)
print("A list of miscellaneous information in the Seurat object:")
print(seurat_obj@misc)
print("Version of Seurat this object was built under:")
print(seurat_obj@version)
print("A list of logged commands run on this Seurat object:")
print(seurat_obj@commands)
print("A list of miscellaneous data generated by other tools:")
print(seurat_obj@tools)

sink()

# Create a list of the genes and cells in the object
if (gene_list== "yes" || cell_list == "yes"){
	obj <- seurat_obj@assays
	# Object has been normalised with SCTransform
	if (seurat_obj@active.assay == "SCT"){
		genes <- obj$SCT@counts@Dimnames[1]
		cells <- obj$SCT@counts@Dimnames[2]
	# Object has been normalised with the global scaling normalisation
	} else if (!is.null(seurat_obj@commands$NormalizeData.RNA)){
		genes <- obj$RNA@var.features
		cells <- obj$RNA@counts@Dimnames[2]
	# Object consists of multiple samples that have been integrated
	} else if (seurat_obj@active.assay == "integrated") {
		genes <- obj$integrated@data@Dimnames[1]
		cells <- obj$integrated@data@Dimnames[2]
	# Object hasn't been normalised
	} else {
		genes <- obj$RNA@counts@Dimnames[1]
		cells <- obj$RNA@counts@Dimnames[2]
	}
	# nothing found?
	# Write out the gene list
	if (gene_list== "yes") {
		names(genes)[1] <- "Genes"
		write.table(genes, file="gene_list.tsv", sep="\t", row.names=T, col.names=T, quote=F)
	}
	# Write out the cell list
	if (cell_list == "yes") {
		names(cells)[1] <- "Cells"
		write.table(cells, file="cell_list.tsv", sep="\t", row.names=T, col.names=T, quote=F)
	}
}

# Write out the meta.data data frame
write.table(as.data.frame(as.matrix(seurat_obj@meta.data)), file = "meta_data.tsv", sep = "\t", row.names = T, col.names = T, quote = F)





#EOF

