# TOOL single-cell-extract-information.R: "Extract information from Seurat object" (This tool extracts data from Seurat object.)  
# INPUT OPTIONAL seurat_obj.Robj: "Seurat object" TYPE GENERIC
# INPUT OPTIONAL combined_seurat_obj.Robj: "Combined seurat object" TYPE GENERIC
# INPUT OPTIONAL reference: "Seurat object stored in an RDS file " TYPE GENERIC 
# OUTPUT OPTIONAL slots.txt
# OUTPUT OPTIONAL meta_data.tsv
# RUNTIME R-4.2.3-single-cell
# TOOLS_BIN ""  

library(dplyr, quietly = TRUE)
library(Seurat, quietly = TRUE)

# Load the R-Seurat-object (called seurat_obj)
if (file.exists("reference") ){
	seurat_obj <- readRDS("reference")
}
if (file.exists("seurat_obj.Robj") ){
	load("seurat_obj.Robj")
}
if (file.exists("combined_seurat_obj.Robj") ){
	load("combined_seurat_obj.Robj")
	seurat_obj <- data.combined
}
# Create a text file of the different slots in the Seurat object
sink("slots.txt")

print("Assays in the seurat object: ")
print(seurat_obj@assays)
print("Active assay in the object: ")
print(seurat_obj@active.assay)
print("Active cluster identity in the cluster: ")
print(head(seurat_obj@active.ident))
print("List of graph objects in the seurat object:")
print(seurat_obj@graphs)
print("List of neighbor objects in the seurat object:")
print(seurat_obj@neighbors)
print("List of dimensional reductions for this object:")
print(seurat_obj@reductions)
print("List of spatial image objects in this object:")
print(seurat_obj@images)
print("Name of the project:")
print(seurat_obj@project.name)
print("A list of miscellaneous information in the Seurat object:")
print(seurat_obj@misc)
print("Version of Seurat this object was built under:")
print(seurat_obj@version)
print("A list of logged commands run on this Seurat object:")
print(seurat_obj@commands)
print("A list of miscellaneous data generated by other tools:")
print(seurat_obj@tools)

sink()

# Write out the meta.data data frame
write.table(as.data.frame(as.matrix(seurat_obj@meta.data)), file = "meta_data.tsv", sep = "\t", row.names = T, col.names = T, quote = F)





#EOF

